### ISSUE TITLE
session_token or api_key

### ISSUE THREAD

**Issue by JimmyCozza** [fbptech/locate-dev-docs#3]
Hey, question about your documented Auth strategy.

These docs (https://fbptech.github.io/locate-dev-docs//#basic_auth) describe your API as using Basic Auth, but not the one built into the http spec.  It says I should be receiving a `session_token` in the response, which I'd then use (encoded) in the subsequent responses.

Testing this out, it appears that a POST to /login gives me a 200 status code with whatever HTML you render.  No `session_token` to be found anywhere in the body (not that HTML would be a good delivery mechanism for a token), cookies or headers.

I do, however, get an `api_key` in the cookies...but there's no mention of what to do with anything named `api_key`  

Looks like your swagger docs (https://dev.locateinv.com/apidocs/v0) have a little input at the top for the api_key, but no explanation of how to use it in conjunction with the API.  Those docs don't seem to mention session_token.

Are either of these docs up to date, or is there a more updated version somewhere else?

**Comment by JimmyCozza** [comment]
After playing around with some common api_key approaches that I have experienced before, it looks like you accept the query parameter `?api_key=` in place of a base64encode(session_token:session_token)? 

Maybe you do support both, but I think the docs could be a little more clear there.  Would you be open to a PR with some clarification on your Getting Connected section?

**Comment by nschiffelbein** [comment]
Hi Jimmy,

We accept both basic auth or URL parameter based passing of the session_token value. As for receiving the session token you'll want to make sure you include the "Accepts" header on your /login POST so LOCATE knows you're authenticating as code rather than a human trying to access the LOCATE UI. This will return a JSON response with the session token. We'd definitely be open to a PR if you think there is a clearer way to express this.

**Comment by JimmyCozza** [comment]
Thanks for that quick response.  You're right.  I was using "Accept: */*".  

Out of curiosity, will I get a different API experience if I use `session_token` vs `?api_key`?  Or do they both work equally in your API?

**Comment by nschiffelbein** [comment]
Functionally both are identical on the LOCATE side. From a security perspective Basic Auth is better because it's encrypted in the headers of a request whereas the URL parameter can often be seen in transit. I use the URL parameter when testing quick requests, and the Basic Auth header for final production code for this reason.

**Comment by JimmyCozza** [comment]
Thanks again.  I'll stew on anything I can write to help be more clear in those docs, but you're right on the money that I just sent the wrong header so that's on me.

Appreciate your help.
